// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Reservation struct {
	ID           int32
	Name         string
	PartySize    int32
	Time         time.Time
	RestaurantID int32
	TableID      int32
	UserID       int32
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Restaurant struct {
	ID                  int32
	Name                string
	DietaryRestrictions []string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Table struct {
	ID           int32
	Capacity     int32
	IsReserved   bool
	RestaurantID int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID          int32
	FirstName   string
	LastName    string
	PhoneNumber string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
