// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tables.sql

package database

import (
	"context"
)

const createRestaurantTable = `-- name: CreateRestaurantTable :one
INSERT INTO tables (restaurant_id, capacity)
VALUES ($1, $2)
RETURNING id, capacity, is_reserved, restaurant_id, created_at, updated_at
`

type CreateRestaurantTableParams struct {
	RestaurantID int32
	Capacity     int32
}

func (q *Queries) CreateRestaurantTable(ctx context.Context, arg CreateRestaurantTableParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, createRestaurantTable, arg.RestaurantID, arg.Capacity)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.Capacity,
		&i.IsReserved,
		&i.RestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
